const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema({
  role: {
    type: String,
    enum: ['user', 'assistant', 'system'],
    required: true
  },
  content: {
    type: String,
    required: true
  },
  timestamp: {
    type: Date,
    default: Date.now
  },
  // Optional metadata for the message
  metadata: {
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Project'
    },
    chapterNumber: {
      type: Number,
      min: 0,
      max: 5,
      default: 0 // 0 = general conversation, 1-5 = chapter-specific
    },
    messageType: {
      type: String,
      enum: ['general', 'project_topic', 'chapter_help', 'review_edit', 'topic_generation'],
      default: 'general'
    }
  }
});

const conversationSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: [100, 'Conversation title cannot be more than 100 characters']
  },
  // Auto-generated title from first user message if not provided
  autoGeneratedTitle: {
    type: Boolean,
    default: false
  },
  // Conversation type
  type: {
    type: String,
    enum: ['general', 'project_specific', 'topic_generation'],
    default: 'general'
  },
  // Reference to project if this conversation is project-related
  project: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Project'
  },
  // All messages in the conversation
  messages: [messageSchema],
  // Conversation status
  status: {
    type: String,
    enum: ['active', 'archived', 'deleted'],
    default: 'active'
  },
  // Metadata
  messageCount: {
    type: Number,
    default: 0
  },
  lastMessageAt: {
    type: Date,
    default: Date.now
  },
  // Tags for better organization
  tags: [{
    type: String,
    trim: true
  }],
  // AI model used for this conversation
  aiModel: {
    type: String,
    default: 'gemini-flash-latest'
  }
}, {
  timestamps: true
});

// Indexes for better performance
conversationSchema.index({ user: 1, status: 1, lastMessageAt: -1 });
conversationSchema.index({ user: 1, type: 1 });
conversationSchema.index({ project: 1 });

// Update message count and last message timestamp before saving
conversationSchema.pre('save', function(next) {
  this.messageCount = this.messages.length;
  if (this.messages.length > 0) {
    this.lastMessageAt = this.messages[this.messages.length - 1].timestamp;
  }
  next();
});

// Auto-generate title from first user message if title is not provided
conversationSchema.methods.generateTitleFromFirstMessage = function() {
  if (this.title || this.messages.length === 0) return;

  const firstUserMessage = this.messages.find(msg => msg.role === 'user');
  if (firstUserMessage) {
    // Take first 50 characters of the message as title
    const title = firstUserMessage.content.substring(0, 50);
    this.title = title.length < firstUserMessage.content.length ? title + '...' : title;
    this.autoGeneratedTitle = true;
  }
};

// Static method to get user's conversations
conversationSchema.statics.getUserConversations = function(userId, options = {}) {
  const { limit = 50, skip = 0, status = 'active', type } = options;

  const query = { user: userId, status };

  if (type) {
    query.type = type;
  }

  return this.find(query)
    .sort({ lastMessageAt: -1 })
    .limit(limit)
    .skip(skip)
    .populate('project', 'title topic')
    .select('title type project messageCount lastMessageAt createdAt autoGeneratedTitle');
};

// Method to add a message to the conversation
conversationSchema.methods.addMessage = function(messageData) {
  const message = {
    role: messageData.role,
    content: messageData.content,
    timestamp: new Date(),
    metadata: messageData.metadata || {}
  };

  this.messages.push(message);
  this.lastMessageAt = message.timestamp;
  this.messageCount = this.messages.length;

  return this.save();
};

module.exports = mongoose.model('Conversation', conversationSchema);
